import AdventureFinishChoices from '../components/AdventureFinishChoices.jsx'
import { useState } from 'react'
import YaagviCharacter from '../components/YaagviCharacter.jsx'
import { useSpeech } from '../hooks/useSpeech.js'
import { MARKET_ITEMS, marketTotals, marketReasons, normalizeMarket, applyMarketAction } from '../utils/marketMission.js'
import './market-mission.css'

export function MarketItem({ id }) {
 const item=MARKET_ITEMS.find(i=>i.id===id)
 return <svg viewBox="0 0 120 120" className="market-item-art" aria-hidden="true"><ellipse cx="60" cy="104" rx="35" ry="7" fill="#182e3520"/>{id==='apple'?<><path d="M60 36C20 14 10 61 30 89Q45 108 60 97Q83 108 95 86C116 41 85 19 60 36" fill={item.colour}/><path d="M60 37Q56 18 64 11" fill="none" stroke="#5d5736" strokeWidth="7"/><path d="M65 27Q80 4 95 19Q83 36 65 27" fill="#719363"/><path d="M31 53Q27 62 30 71" stroke="#f5baa0" strokeWidth="6" strokeLinecap="round" fill="none"/></>:id==='banana'?<><path d="M30 18Q13 100 95 88L102 72Q46 88 40 24Z" fill={item.colour} stroke="#b78329" strokeWidth="3"/><path d="M33 27Q29 82 87 85" fill="none" stroke="#fff0aa" strokeWidth="5"/><path d="M29 18L39 22M95 88L102 72" stroke="#6c5836" strokeWidth="7"/></>:id==='water'?<><rect x="43" y="12" width="34" height="16" rx="5" fill="#436675"/><path d="M44 28H76L87 45V98Q60 111 33 98V45Z" fill={item.colour}/><rect x="33" y="55" width="54" height="27" fill="#f5f2dd"/><path d="M60 58Q39 78 60 80Q81 78 60 58" fill="#588fba"/></>:<><path d="M35 32L45 14H80L89 32V104H35Z" fill={item.colour}/><path d="M35 32H89L80 14H45Z" fill="#f4c28c"/><path d="M75 42V10L90 5" fill="none" stroke="#537967" strokeWidth="6"/><circle cx="62" cy="71" r="19" fill="#fff4cf"/><path d="M62 54V88M45 71H79M50 59L74 83M50 83L74 59" stroke="#e0a13e" strokeWidth="2"/></>}</svg>
}
export function MarketHome({progress,profileName,onPlay,onExplore,onParents,onSwitchProfiles}){
 const [journal,setJournal]=useState(false)
 const {state,updatedAt}=normalizeMarket(progress.marketMission)
 const resume=updatedAt>0&&state.phase!=='complete'
 return <main className="market-page"><div className="market-shell"><header className="market-nav"><strong>bloom <span>SUPER KIDS · 7–9</span></strong><div><button onClick={onSwitchProfiles}>Profiles</button>{onParents&&<button onClick={onParents}>Parents</button>}</div></header>
 <section className="market-home"><p className="market-kicker">YOUR MISSION DESK</p><h1>{journal?'Your discoveries':`Ready, ${profileName||'explorer'}?`}</h1>
 {journal?<div className="market-journal"><h2>{state.report?'A plan that adds up':'Your first mission is waiting'}</h2><p>{state.report?`You covered four friends with ${state.report.cost} coins and ${state.report.left} left. What would you choose next time?`:'Plan a picnic, check the numbers and explain your choice.'}</p><button className="market-primary" onClick={()=>setJournal(false)}>Back to missions</button></div>:<div className="market-mission-card"><div className="market-home-copy"><p className="market-kicker">MISSION 01 · THE MINI-MARKET</p><h2>The picnic budget</h2><p>Four friends. Twelve coins.<br/>Can your plan cover everyone?</p><div className="market-tags"><span>Plan</span><span>Calculate</span><span>Explain</span></div><button className="market-primary" onClick={onPlay}>{resume?'Continue mission':state.report?'Try a different plan':'Start mission'} →</button></div><div className="market-stall" aria-hidden="true"><div className="market-awning"/><div className="market-stall-sign">THE LITTLE MARKET</div><div className="market-stall-shelf">{MARKET_ITEMS.map(i=><div key={i.id}><MarketItem id={i.id}/><b>{i.price} ●</b></div>)}</div><div className="market-stall-base">GOOD IDEAS START WITH A PLAN.</div></div></div>}
 <nav className="market-home-links" aria-label="Super Kids activities"><button onClick={onExplore}>Explore all subjects ↗</button><button onClick={()=>setJournal(v=>!v)}>{journal?'My missions':'My discoveries'} ↗</button></nav></section></div></main>
}

export default function MarketMission({progress,update,onBack,onExplore}){
 const {state:s}=normalizeMarket(progress.marketMission),totals=marketTotals(s.counts)
 const {speak,speaking,stopSpeaking}=useSpeech()
 const [showHelp,setShowHelp]=useState(false)
 const dispatch=a=>{const at=Date.now();update(p=>applyMarketAction(p,a,at))}
 const phase=s.phase,complete=phase==='complete'
 const headings={plan:'What will you buy?',total:'What will your basket cost?',change:'How many coins will be left?',reason:'Why does this plan work?',complete:'Your plan adds up.'}
 let feedback=phase==='plan'?'Choose one fruit and one drink for each of four friends. You have 12 coins.':phase==='total'?'Multiply each price by its quantity. Then add the groups.':phase==='change'?`Your basket costs ${totals.cost} coins. You started with 12.`:phase==='reason'?'Choose a reason that describes your plan. Different choices can work.':'You planned, checked and made a choice. Take the idea into the real world.'
 if(s.feedback==='empty')feedback=phase==='plan'?'Choose something for the basket first.':'Enter a number first. Zero is a number too.'
 if(s.feedback==='quantity')feedback=`Your basket has ${totals.fruit} fruits and ${totals.drink} drinks. We need exactly four of each.`
 if(s.feedback==='budget')feedback=`Your calculation is right: ${totals.cost} coins. That is ${totals.cost-12} more than we have. Swap some items for a cheaper choice.`
 if(s.feedback==='total')feedback='Check the price of each group, then add the groups together. You can ask for the working.'
 if(s.feedback==='change')feedback=`Think: ${totals.cost} plus how many makes 12?`
 const chooseHelp=()=>{dispatch({type:'HELP'});setShowHelp(v=>!v)}
 const move=a=>{setShowHelp(false);dispatch(a);stopSpeaking()}
 const selected=MARKET_ITEMS.filter(i=>s.counts[i.id]>0)
 return <main className="market-page"><div className="market-shell"><header className="market-nav"><button onClick={onBack}>← My missions</button><strong>The mini-market</strong><button onClick={()=>speaking?stopSpeaking():speak(`${headings[phase]} ${feedback}`)}>{speaking?'Stop voice':'♫ Read to me'}</button></header>
 <nav className="market-steps" aria-label="Mission progress">{['plan','total','change','reason'].map((p,i)=><span key={p} aria-current={phase===p?'step':undefined} className={phase===p?'active':complete||['plan','total','change','reason'].indexOf(phase)>i?'done':''}>{i+1}. {['Choose','Cost','Change','Explain'][i]}</span>)}</nav>
 <div className="market-title"><p className="market-kicker">THE PICNIC BUDGET · PRETEND MARKET COINS</p><h1>{headings[phase]}</h1></div>
 <aside className="market-guide"><YaagviCharacter size={80} state={complete?'celebrate':s.feedback?'think':showHelp?'point':'idle'} reactionKey={`${phase}-${s.attempts.total}-${s.attempts.change}-${showHelp}`} talking={speaking}/><p role="status" aria-live="polite">{feedback}</p></aside>
 {complete?<section className="market-finish"><div className="market-receipt"><h2>Your picnic plan</h2>{selected.map(i=><p key={i.id}><span>{s.counts[i.id]} × {i.name}</span><strong>{s.counts[i.id]*i.price} coins</strong></p>)}<p className="market-receipt-total"><span>Total</span><strong>{totals.cost} coins</strong></p><p><span>Left for later</span><strong>{12-totals.cost} coins</strong></p></div><div><h2>Try it away from the screen</h2><p>Make a pretend shop with a grown-up. Set prices for three things. Plan for two people with six counters. What would you change?</p><p className="market-note">Your grown-up can find your first completed plan in Parents → Weekly Story.</p><AdventureFinishChoices nextLabel="Choose another activity" onContinue={onExplore} onFinish={onBack} onReplay={()=>move({type:'REPLAY'})} replayLabel="Try another basket"/></div></section>:<div className="market-workspace">
 <section className="market-main">{phase==='plan'?<><div className="market-shop-heading"><span>THE LITTLE MARKET</span><span>Prices per item</span></div><div className="market-products">{MARKET_ITEMS.map(i=><article key={i.id}><MarketItem id={i.id}/><div><h2>{i.name}</h2><p>{i.price} {i.price===1?'coin':'coins'} each</p></div><div className="market-quantity"><button aria-label={`Remove ${i.single}`} disabled={!s.counts[i.id]} onClick={()=>dispatch({type:'QUANTITY',id:i.id,delta:-1})}>−</button><output aria-label={`${i.name} selected`}>{s.counts[i.id]}</output><button aria-label={`Add ${i.single}`} disabled={s.counts[i.id]===4} onClick={()=>dispatch({type:'QUANTITY',id:i.id,delta:1})}>+</button></div></article>)}</div></>:phase==='reason'?<section className="market-reasons"><h2>My reason</h2><p>Pick the reason closest to yours. This is your preference, not a test of what you like.</p>{marketReasons(s.counts).map(r=><button key={r.id} onClick={()=>move({type:'FINISH',reason:r.id})}>{r.label} <span>Finish →</span></button>)}</section>:<form className="market-calculation" onSubmit={e=>{e.preventDefault();move({type:'CHECK'})}}><div className="market-equation">{phase==='total'?selected.map((i,n)=><span key={i.id}>{n>0&&<b> + </b>}{s.counts[i.id]} × {i.price}</span>):<span>12 − {totals.cost}</span>}<span> = ?</span></div><label htmlFor="market-answer">{phase==='total'?'Total cost in coins':'Coins left'}</label><div className="market-answer"><input id="market-answer" autoComplete="off" inputMode="numeric" pattern="[0-9]*" maxLength={2} value={s.answer} onChange={e=>dispatch({type:'ANSWER',value:e.target.value})}/><button className="market-primary" type="submit">Check my answer</button></div><button type="button" className="market-secondary" onClick={chooseHelp}>{showHelp?'Hide working':'Show the working'}</button>{showHelp&&<div className="market-working">{phase==='total'?<>{selected.map(i=><p key={i.id}>{s.counts[i.id]} × {i.price} = {s.counts[i.id]*i.price} coins for {i.name.toLowerCase()}</p>)}<p>Add those group costs together.</p></>:<><p>Start at {totals.cost}. Count up to 12.</p><div className="market-counter-line">{Array.from({length:12-totals.cost},(_,n)=><span key={n}>{totals.cost+n+1}</span>)}</div><p>{totals.cost===12?'You spent all 12. None are left.':'Count the steps. That is how many coins remain.'}</p></>}</div>}</form>}
 </section><aside className="market-basket"><p className="market-kicker">YOUR BASKET</p><h2>For four friends.</h2><div className="market-coverage"><span className={totals.fruit===4?'met':''}>Fruit {totals.fruit}/4</span><span className={totals.drink===4?'met':''}>Drinks {totals.drink}/4</span></div><ul>{selected.length?selected.map(i=><li key={i.id}><span>{s.counts[i.id]} × {i.name}</span><span>{i.price} each</span></li>):<li>Your choices go here.</li>}</ul><p className="market-budget">Budget <strong>12 coins</strong></p>{['change','reason'].includes(phase)&&<p>Basket cost: <strong>{totals.cost} coins</strong></p>}{phase==='reason'&&<p>Coins left: <strong>{12-totals.cost}</strong></p>}{phase==='plan'?<button className="market-primary" onClick={()=>move({type:'CHECK_PLAN'})}>Check my basket →</button>:<button className="market-secondary" onClick={()=>move({type:'EDIT'})}>Change my basket</button>}<p className="market-note">Pretend prices. No real purchases.</p></aside></div>}
 </div></main>
}

