import React from 'react'
import { motion } from 'framer-motion'

const DESTINATIONS = {
  phonics:{icon:'🎤',place:'Echo Jungle',title:'Sound Pop',mission:'Listen, spot the sound, and wake the singing birds.',pos:'18% 46%',pose:'wave'}, math:{icon:'🔢',place:'Number Falls',title:'Number World',mission:'Solve a number puzzle to reveal the next map clue.',pos:'37% 38%',pose:'point'}, tricky:{icon:'⭐',place:'Starry Caves',title:'Star Catch',mission:'Catch the tricky words before their sparkle fades.',pos:'9% 64%',pose:'celebrate'}, story:{icon:'📖',place:'Story Tree',title:'Story Room',mission:'Open today’s story and find the hidden sound clues.',pos:'14% 38%',pose:'read'},
  shapes:{icon:'🔷',place:'Shape River',title:'Shape World',mission:'Match shapes to rebuild the explorer bridge.',pos:'46% 64%',pose:'think'}, logic:{icon:'🧩',place:'Puzzle Pass',title:'Puzzle Quest',mission:'Plan the moves and guide Yaagvi through the pass.',pos:'59% 38%',pose:'think-alt'}, davinci:{icon:'🎨',place:'Rainbow Mountain',title:'Da Vinci Studio',mission:'Create a picture to colour the mountain trail.',pos:'65% 29%',pose:'point'}, shop:{icon:'🛍️',place:'Treasure Market',title:'Coin Shop',mission:'Count the coins and pack the right explorer supplies.',pos:'82% 58%',pose:'wave'},
  worldgk:{icon:'🌍',place:'World Lookout',title:'World Explorer',mission:'Discover a place and add it to Yaagvi’s travel map.',pos:'28% 22%',pose:'point'}, science:{icon:'🔬',place:'Wonder Springs',title:'Wonder Lab',mission:'Choose a mystery and uncover why it happens.',pos:'75% 45%',pose:'think'}, planets:{icon:'🪐',place:'Moon Camp',title:'Planet World',mission:'Launch beyond the map and discover a new world.',pos:'50% 18%',pose:'celebrate'}, anatomy:{icon:'🫀',place:'Body Basecamp',title:'My Body',mission:'Find a body clue and learn how it helps you explore.',pos:'32% 70%',pose:'point'},
  exercise:{icon:'🏃',place:'Movement Meadow',title:'Fun Exercise',mission:'Move with Yaagvi and charge your adventure energy.',pos:'70% 72%',pose:'dance'}, arcade:{icon:'🎮',place:'Treasure Arcade',title:'Game Arcade',mission:'Spend your earned play pass on a quick game.',pos:'89% 64%',pose:'celebrate'}, sacred:{icon:'🕊️',place:'Story Temple',title:'Sacred Stories',mission:'Listen to a story of kindness from around the world.',pos:'84% 27%',pose:'read'}, piggybank:{icon:'🐷',place:'Coin Cove',title:'Piggy Bank',mission:'Sort and save coins for Yaagvi’s next expedition.',pos:'91% 72%',pose:'wave'},
}

const TODDLER_DESTINATIONS = {
  colours:{icon:'🌈',place:'Rainbow Garden',title:'Colour Play',mission:'Tap a colour and make the garden glow.',pos:'18% 46%',pose:'wave'}, shapes:{icon:'🔵',place:'Shape Pond',title:'Shape Play',mission:'Find the matching shape with Yaagvi.',pos:'42% 62%',pose:'point'}, numbers:{icon:'🔢',place:'Counting Falls',title:'Number Play',mission:'Count the pictures and tap the number.',pos:'35% 34%',pose:'celebrate'}, animals:{icon:'🐘',place:'Animal Jungle',title:'Animal Friends',mission:'Meet an animal and listen to its sound.',pos:'12% 60%',pose:'wave'}, fruits:{icon:'🍎',place:'Fruit Orchard',title:'Fruit Basket',mission:'Find a yummy fruit for the picnic.',pos:'72% 62%',pose:'point'}, bodyparts:{icon:'👋',place:'Wiggle Meadow',title:'My Body',mission:'Point, tap, and wiggle with Yaagvi.',pos:'62% 36%',pose:'dance'}, alphabet:{icon:'🔤',place:'Letter Tree',title:'Alphabet Play',mission:'Find one letter and hear its sound.',pos:'20% 28%',pose:'read'},
}

const JUNIOR_DESTINATIONS = {
  timestables:{icon:'✖️',place:'Multiplier Mine',title:'Times Tables',mission:'Crack a multiplication code to open the next tunnel.',pos:'36% 44%',pose:'point'}, fractions:{icon:'🍕',place:'Fraction Falls',title:'Fractions',mission:'Divide the supplies fairly and recover a map piece.',pos:'45% 62%',pose:'think'}, reading:{icon:'📚',place:'Story Ruins',title:'Reading Quest',mission:'Read closely and uncover the clue hidden in the text.',pos:'16% 38%',pose:'read'}, spelling:{icon:'✍️',place:'Word Woods',title:'Spelling Mission',mission:'Repair the missing words along the forest trail.',pos:'23% 55%',pose:'think-alt'}, wordproblems:{icon:'🧭',place:'Problem Pass',title:'Word Problems',mission:'Use the clues to calculate a safe route forward.',pos:'58% 39%',pose:'point'}, grammar:{icon:'📝',place:'Grammar Grove',title:'Grammar Lab',mission:'Rebuild each sentence to reveal the explorer message.',pos:'28% 68%',pose:'think'}, science:{icon:'🧪',place:'Discovery Springs',title:'Science Lab',mission:'Investigate today’s question and record your discovery.',pos:'76% 43%',pose:'think-alt'}, worldmap:{icon:'🌍',place:'Atlas Lookout',title:'World Map',mission:'Locate a new place and pin it to the expedition map.',pos:'70% 24%',pose:'point'}, spirituality:{icon:'🕊️',place:'Wisdom Temple',title:'Wisdom Stories',mission:'Explore a story about values, choices, and kindness.',pos:'84% 29%',pose:'read'}, games:{icon:'🎮',place:'Treasure Arcade',title:'Game Zone',mission:'Use your earned game pass for a short challenge.',pos:'88% 65%',pose:'celebrate'}, exercise:{icon:'🏃',place:'Training Camp',title:'Movement Break',mission:'Recharge your focus with a quick movement challenge.',pos:'68% 72%',pose:'dance'}, piggybank:{icon:'🐷',place:'Coin Cove',title:'Money Mission',mission:'Plan, count, and save for the next expedition.',pos:'91% 72%',pose:'wave'},
}

export default function ModuleArrival({ moduleId, profileName, onStart, onBack, ageGroup='early' }) {
  const source=ageGroup==='toddler'?TODDLER_DESTINATIONS:ageGroup==='junior'?JUNIOR_DESTINATIONS:DESTINATIONS
  const d=source[moduleId]; if(!d) return null
  const toddler=ageGroup==='toddler', junior=ageGroup==='junior'
  return <motion.div className="fixed inset-0 z-[260] flex items-center justify-center bg-[#2a1740]/70 p-4 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>
    <motion.section className="relative w-full max-w-3xl overflow-hidden rounded-[32px] border-4 border-[#fff1cf] shadow-2xl" initial={{y:30,scale:.92}} animate={{y:0,scale:1}} exit={{y:20,scale:.96}} transition={{type:'spring',stiffness:260,damping:22}}>
      <div className="absolute inset-0 bg-cover" style={{backgroundImage:'url(/treasure-map-bg.png)',backgroundPosition:d.pos}}/><div className="absolute inset-0 bg-gradient-to-r from-[#fff4d8]/95 via-[#fff4d8]/82 to-[#fff4d8]/55"/>
      <div className="relative grid min-h-[430px] items-center gap-2 p-6 sm:grid-cols-[1fr_240px] sm:p-10"><div>
        <p className="font-bubble text-sm uppercase tracking-[.18em] text-[#9a3412]">📍 {toddler?'Let’s visit':junior?'Mission location':'Arrived at'} {d.place}</p><div className="mt-3 flex items-center gap-3"><span className="text-5xl">{d.icon}</span><h2 className="font-bubble text-4xl leading-tight text-[#3b1607] sm:text-5xl">{d.title}</h2></div>
        <p className="mt-4 max-w-md font-round text-xl font-bold leading-snug text-[#6b351b]">{d.mission}</p><p className="mt-3 font-round text-sm font-semibold text-[#9a5b35]">{toddler?'One tiny activity · big pictures · happy celebration':junior?'Focused mission · earn XP · recover treasure':'One mission · a few minutes · stars move the adventure forward'}</p>
        <div className="mt-7 flex gap-3"><motion.button whileTap={{scale:.94}} onClick={()=>{ window.dispatchEvent(new CustomEvent('bloom:module-started',{detail:{moduleId,ageGroup}})); onStart?.() }} className="min-h-14 flex-1 rounded-2xl bg-gradient-to-r from-orange-500 to-pink-500 px-6 font-bubble text-xl text-white shadow-lg">{toddler?'Play! →':junior?'Start mission →':'Let’s explore →'}</motion.button><button onClick={onBack} className="min-h-14 rounded-2xl border-2 border-[#7c3f20]/20 bg-white/70 px-5 font-bubble text-[#6b351b]">Map</button></div>
      </div><motion.div className="relative mx-auto h-60 w-52 self-end sm:h-80 sm:w-60" animate={{y:[0,-8,0],rotate:[-1,1,-1]}} transition={{duration:3,repeat:Infinity,ease:'easeInOut'}}><div className="absolute inset-x-5 bottom-4 h-8 rounded-full bg-[#6b351b]/20 blur-md"/><img src={`/yaagvi-poses/${d.pose}.png`} alt={`Yaagvi welcomes ${profileName||'the explorer'}`} className="relative h-full w-full object-contain drop-shadow-xl"/></motion.div></div>
    </motion.section>
  </motion.div>
}
